@startuml global sequence diagram
skinparam maxMessageSize 300

actor "User" as user
' actor "Voter" as user1
' actor "Candidate" as user2
' actor "KPU" as user3
participant "Frontend" as system1
participant "Backend" as system2
participant "Blockchain" as system3

group View Voting
    user -> system1: View Voting

    system1 -> system2 ++: send user request

    system2 -> system3: Request voting data
    activate system3
    system3 -> system2: Response voting data
    deactivate system3

    system2 -> system1 : Show Voting status
    system2 --
    

end
@enduml